#!/usr/bin/env ruby
# frozen_string_literal: true

require 'time'

require 'indexen'

include Indexen

class Root < Index
  def self.child
    Course
  end

  def self.template
    <<~EOF
      <%= body %>

      ### Dersler

      <%- children.each do |course| %>
      - [<%= course.identifier %>](<%= course.slug %>)
      <%- end %>
    EOF
  end
end

class Course < Index
  def self.child
    Lecture
  end

  def self.template
    <<~EOF
      <%= body %>

      ### Materyal

      | Tür   | Materyal |
      |:----- |:-------- |
      | Sunum | <%= Support.icon('file', pdf) %> |

      <%- unless children.empty? %>
      ### Oturum

      | Tarih | Notlar | Kayıt |
      |:----- |:------ |:----- |
      <%- children.each do |lecture| -%>
      | <%= lecture.date %> | <%= Support.icon('github', lecture.notes) %> | <%= Support.icon('youtube', lecture.recording) %> |
      <%- end %>
      <% end -%>
    EOF
  end

  def pdf
    'slides.pdf'
  end

  def audience
    local.audience
  end

  def identifier
    "#{title} / #{audience}"
  end
end

class Lecture < Index
  def self.pattern
    /^\d{12}$/.freeze
  end

  def self.indexfile
    'README.md'
  end

  def title
    Time.strptime(name, '%Y%m%d%H%M').strftime('%Y-%m-%d %R')
  end

  def date
    title
  end

  def notes
    File.join global.repository, 'tree', 'HEAD', slug
  end

  def recording
    get(:recording)
  end

  def renderable?
    false
  end
end

def main(argv)
  abort 'Usage: $PROGRAM_NAME <input directory> <output directory>' unless argv.size == 2

  Indexen.run(Root, indir: argv.shift, outdir: argv.shift) do |global|
    global.repository = 'https://github.com/roktas/classroom'
  end
end

main ARGV if __FILE__ == $PROGRAM_NAME
